[package]
name = "physics_engine_2d"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
num-traits = "0.2" 
minifb = "0.24"

[dev-dependencies]
# For visualization examples
minifb = "0.24"